# sysinfo - custom reminder function for your .bashrc or .zshrc file
sysinfo() {
  echo "Feeling forgetful are we?\n"
  echo "ls        - List directory contents."
  echo "cd        - Change the current directory."
  echo "pwd       - Returns working directory name."
  echo "cp        - Copy files or directories."
  echo "mv        - Move files or directories."
  echo "rm        - Remove files or directories."
  echo "mkdir     - Create a new directory."
  echo "chmod     - Change file mode bits."
  echo "chown     - Change file owner and group."
  echo "grep      - Search for a pattern in files."
  echo "find      - Search for files in a directory hierarchy."
  echo "ps        - Shows process status."
  echo "top       - Display Linux processes."
  echo "uname     - Prints basic information about the operating system name and system hardware."
  echo "whoami    - Displays current username."
  echo "id        - Returns users identity."
  echo "hostname  - Sets or prints the name of current host system."
  echo "ifconfig  - Assign or view an address to a network interface and/or configure network interface parameters."
  echo "ip        - Show or manipulate routing, network devices, interfaces and tunnels."
  echo "netstat   - Shows network status."
  echo "ss        - Another utility to investigate sockets."
  echo "who       - Displays who is logged in."
  echo "env       - Prints environment or sets and executes command."
  echo "lsblk     - Lists block devices."
  echo "lsusb     - Lists USB devices."
  echo "lsof      - Lists opened files."
  echo "lspci     - Lists PCI devices."
}
